package view;

import DAO.DAOUsuario;
import DAO.InterfaceDAOUsuario;
import controller.ControllerUsuario;
import controller.InterfaceControllerUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUsuario;

public class TelaUsuario extends javax.swing.JInternalFrame {

    InterfaceDAOUsuario interfaceDAOUsuario = new DAOUsuario();
    InterfaceControllerUsuario IControllerUsuario = new ControllerUsuario(interfaceDAOUsuario);

    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelClientes = new ArrayList<>();
    String salvarAlterar = "salvar";
    
    public static int funcaoUsuario = 0;

    public TelaUsuario() {
        initComponents();
        carregarUsuarios();
        desabilitaCampos(false);
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlterar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbFuncao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        txtSenha = new javax.swing.JPasswordField();
        cbEstado = new javax.swing.JComboBox<>();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(746, 503));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        jLabel9.setText("Matricula:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 62, -1, -1));

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel10.setText("CPF:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        txtCodigo.setEnabled(false);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 73, -1));
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 82, 206, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 11, -1, -1));

        jLabel11.setText("Função:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 62, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 31, 559, -1));

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operador", "Gerente", " " }));
        cbFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncaoActionPerformed(evt);
            }
        });
        getContentPane().add(cbFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 82, 116, -1));

        jLabel3.setText("Endereço:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 262, -1));

        jLabel12.setText("Login: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        jLabel4.setText("Bairro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel13.setText("Senha: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 108, -1, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 432, -1));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 301, -1));

        jLabel5.setText("Cidade: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 197, -1));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 154, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 391, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "RJ", "SP", "BH", "AC" }));
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, -1));

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 162, -1));

        jLabel6.setText("UF:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 26, -1));

        jLabel7.setText("CEP:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 278, -1));

        jLabel8.setText("Telefone:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 710, 170));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        desabilitaCampos(true);
        int linha = tabelaCliente.getSelectedRow();
        int codigoUsuario = (int) tabelaCliente.getValueAt(linha, 0);
        salvarAlterar = "alterar";

        try {
            modelUsuario = IControllerUsuario.getusuarioController(codigoUsuario);
            txtCodigo.setText(String.valueOf(modelUsuario.getIdUser()));
            txtNome.setText(modelUsuario.getNome());
            txtCpf.setText(modelUsuario.getCpf());
            txtMatricula.setText(String.valueOf(modelUsuario.getMatricula()));
            txtEndereco.setText(modelUsuario.getEndereco());
            txtBairro.setText(modelUsuario.getBairro());
            txtCidade.setText(modelUsuario.getCidade());
            txtCep.setText(modelUsuario.getCep());
            txtTelefone.setText(modelUsuario.getTelefone());
            txtLogin.setText(modelUsuario.getLogin());
            txtSenha.setText(modelUsuario.getSenha());
            cbEstado.setSelectedItem(modelUsuario.getEstado());
            //cbFuncao.setSelectedIndex(modelUsuario.getFuncao());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int linha = tabelaCliente.getSelectedRow();
            int codigoCliente = (int) tabelaCliente.getValueAt(linha, 0);
            if (IControllerUsuario.excluirusuarioController(codigoCliente)) {
                JOptionPane.showMessageDialog(this, "Usuario excluido com Sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarUsuarios();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Usuário", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario para excluir", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        desabilitaCampos(false);
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        desabilitaCampos(true);
        limparCampos();
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (salvarAlterar.equals("salvar")) {
            modelUsuario.setNome(txtNome.getText());
            modelUsuario.setMatricula(Integer.parseInt(txtMatricula.getText()));
            modelUsuario.setCpf(txtCpf.getText());
            modelUsuario.setEndereco(txtEndereco.getText());
            modelUsuario.setBairro(txtBairro.getText());
            modelUsuario.setCidade(txtCidade.getText());
            modelUsuario.setCep(txtCep.getText());
            modelUsuario.setTelefone(txtTelefone.getText());
            modelUsuario.setLogin(txtLogin.getText());
            modelUsuario.setSenha(txtSenha.getText());
            modelUsuario.setEstado(cbEstado.getSelectedItem().toString());
            modelUsuario.setFuncao(cbFuncao.getSelectedIndex());

            if (IControllerUsuario.salvarusuarioController(modelUsuario) > 0) {
                JOptionPane.showMessageDialog(this, "Usuário Salvo com Sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarUsuarios();
                desabilitaCampos(false);
                limparCampos();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar usuário", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            modelUsuario.setIdUser(Integer.parseInt(txtCodigo.getText()));
            modelUsuario.setNome(txtNome.getText());
            int conversor = 0;
            try {
                conversor = Integer.parseInt(txtMatricula.getText());
            } catch (Exception e) {
                e.printStackTrace();
            }
            modelUsuario.setMatricula(conversor);
            modelUsuario.setCpf(txtCpf.getText());
            modelUsuario.setEndereco(txtEndereco.getText());
            modelUsuario.setBairro(txtBairro.getText());
            modelUsuario.setCidade(txtCidade.getText());
            modelUsuario.setCep(txtCep.getText());
            modelUsuario.setTelefone(txtTelefone.getText());
            modelUsuario.setEstado(cbEstado.getSelectedItem().toString());
            modelUsuario.setFuncao(cbFuncao.getSelectedIndex());

            if (IControllerUsuario.atualizarusuarioController(modelUsuario)) {
                JOptionPane.showMessageDialog(this, "Usuario Salvo com Sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarUsuarios();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar Usuário", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuncaoActionPerformed
    
    private void desabilitaCampos(boolean condicao) {
        txtNome.setEnabled(condicao);
        txtCpf.setEnabled(condicao);
        txtMatricula.setEnabled(condicao);
        txtLogin.setEnabled(condicao);
        txtSenha.setEnabled(condicao);
        txtEndereco.setEnabled(condicao);
        txtBairro.setEnabled(condicao);
        txtCidade.setEnabled(condicao);
        txtCep.setEnabled(condicao);
        txtTelefone.setEnabled(condicao);
        cbEstado.setEnabled(condicao);
        cbFuncao.setEnabled(condicao);
        btnSalvar.setEnabled(condicao);
    }
    
    private void limparCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtMatricula.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtEndereco.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        txtTelefone.setText("");
        cbEstado.getItemAt(0);
        cbFuncao.getItemAt(0);
    }

    private void carregarUsuarios() {
        listaModelClientes = IControllerUsuario.getListausuarioController();
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        modelo.setNumRows(0);

        int cont = listaModelClientes.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelClientes.get(i).getIdUser(),
                listaModelClientes.get(i).getNome(),
                listaModelClientes.get(i).getCidade(),
                listaModelClientes.get(i).getTelefone()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
